language: node_js
node_js:
- lts/*
cache: yarn
script:
- yarn prettier:check
- yarn tslint
- yarn build
- yarn test
env:
  global:
    - TEST_SERVER_URL=http://localhost:9000
    - secure: M38DpKZwUgYpDI7blyervQUX7/oXuRfOYKEUGWv2FUgVLTvA+FQy68AYKG7k3N29ZgINrj9JkbcSOtP6oA5xQXYxZA4a74JUo5xnNsMmo/jUCSuxU1H+i4lm/WVUrVGNzzzLQiplBJpM+A9IgoqhxzfSartEzPvcxw5Ty8hU17U4wfhDnORY66Gkl/MS3K1MvjZgw6/bnVJ6/RrQtrM1dfAmqrRbW/yfS3hk1xRMN3piz6T1ilO4e+grUlAdmIIUKI0BD25ijnbVZO1KajJUuO9pPjvMWW1dy5Ah9i6wVjw4FrjV5s/11hrbxy7G/uznKzXsFm4MCiPRAn6osTB/4pnEFDp6hR8jxCXDGKlkmU/GL23AgMLyzm4ZWFEBn/NTwmgxgxvl6zYvNLXTTasyUD/o8lCWhrnfd4UdpbThnz/+iDSKXtQl6d6luOVenHH9xoVfqyGWzMCmKQi/XkmRs/MOK4YWerE2XlWy0/CtfbCvhKtQGNdiAu1pA4PF+YtM4fHdkO+aI5Dqmtzm3wM/njbp7vdeKxStNK63vC2Xqf8PzcJhXuk2YF2eLGHl0kygS1Wsq4igQhrChVIki3qS57KEsTlsAmVSpUgm0UIQC9YeR9tbBHj14f7VecOayRidnzFS/ntqclwLHX+J2CDoKB0ayaO5jnzAfnHWln7ES58=
