language: node_js
node_js:
- lts/*
cache: yarn
script:
- yarn prettier:check
- yarn tslint
- yarn build
- yarn test
env:
  global:
  - TEST_SERVER_URL=http://localhost:9000
  - secure: M38DpKZwUgYpDI7blyervQUX7/oXuRfOYKEUGWv2FUgVLTvA+FQy68AYKG7k3N29ZgINrj9JkbcSOtP6oA5xQXYxZA4a74JUo5xnNsMmo/jUCSuxU1H+i4lm/WVUrVGNzzzLQiplBJpM+A9IgoqhxzfSartEzPvcxw5Ty8hU17U4wfhDnORY66Gkl/MS3K1MvjZgw6/bnVJ6/RrQtrM1dfAmqrRbW/yfS3hk1xRMN3piz6T1ilO4e+grUlAdmIIUKI0BD25ijnbVZO1KajJUuO9pPjvMWW1dy5Ah9i6wVjw4FrjV5s/11hrbxy7G/uznKzXsFm4MCiPRAn6osTB/4pnEFDp6hR8jxCXDGKlkmU/GL23AgMLyzm4ZWFEBn/NTwmgxgxvl6zYvNLXTTasyUD/o8lCWhrnfd4UdpbThnz/+iDSKXtQl6d6luOVenHH9xoVfqyGWzMCmKQi/XkmRs/MOK4YWerE2XlWy0/CtfbCvhKtQGNdiAu1pA4PF+YtM4fHdkO+aI5Dqmtzm3wM/njbp7vdeKxStNK63vC2Xqf8PzcJhXuk2YF2eLGHl0kygS1Wsq4igQhrChVIki3qS57KEsTlsAmVSpUgm0UIQC9YeR9tbBHj14f7VecOayRidnzFS/ntqclwLHX+J2CDoKB0ayaO5jnzAfnHWln7ES58=
deploy:
  provider: script
  script: "yarn run publish"
  email: vorobeez@gmail.com
  skip_cleanup: true
  api_key:
    secure: DS8ZVTOZluy4rWz0acYTXoWe0Tnw/JyV8XewS7F86gXKp8pR7Dmr1ttzKNTp9FUqFO+zyaF4v6XCGoSyli4BTmY0TFixasjsQT9CksDrN27jOkGo6ZLC+uLeBwum6IRL54tCgrzyToG+u31/IaRiHdf7fKUwtB3gPCluy3/mmen3v0eT74UxNNBqPn1dbqh83tcYqYG1Gj4c7kiMI/081oOMN39xCADEK0uxFmcUYsnjOVdEbv6WsIjcP63wk1FDPynU++IfS/q8ouSuzNBHAETSmSkYBcZFr/OW+9fjn81Y4YrsNtt2xQim4kcbuHSoJQsgEH7a7ZxxEvepTBBDrh3ODJKU0VfSkCACYvrtmKFxERG6FKNKK8zpVDnZNCww0mOpnTbRwx9BoTkysvG394unLHfn1PF8uQbuas/2wwQN+v9lKczUgXL3pcCKSPdo8pLN4SoVoAbiHRHhI/xbLq0TdCNZ9kpKCFpf4ZoMugLq2sIN/I6oQA6F9YvMbOm8v/WdRo7pWZRNTxST7CrLtnX1NoGET1LnOGj2Tmhc10Bc7BtyvEBEqPXLadPtI+Y1BmjIRtLuFcaZk8EydBV/3Rnn3OD4ZKE34ItqpnkQQckCKwXNpK68MJzVI3rAkTw4rYogMifDCh5kkemFP1E2yhFpjl7JZzbwMB/u6W05ENg=
  on:
    tags: true
    repo: 8base/js-sdk
    branch: master
