language: node_js
node_js:
- lts/*
cache: yarn
script:
- yarn prettier:check
- yarn tslint
- yarn build
- yarn test
env:
  global:
  - TEST_SERVER_URL=http://localhost:9000
  - TEST_WORKSPACE_ID=ck4bg6wtu001808mg6a6u7mjh
  - AUTH_PROFILE_ID=ck5wj03o7002u08mkg61waq28
  - AUTH0_DOMAIN=secure.8base.com
  - AUTH0_CLIENT_ID=lmGkw92PovWoDnNov74bFvrau2g9Efaw
  - secure: O+9L8yqyP/EEV6gfsKMqT9XBGpk4VCJ/K7PoS+C22/nQwAWU3ocaGHNfQxlRsWomDtrecXC1ZlOzDdpKBakAqv55lgwnnzCq7Y3/DCvadeT7cAS+IRphGTSNqGwIxP2RHB9YWGdyv7t8qVywH2+h21Skgyh6Thu1adjFoVFgLwqrMKcBK1MFFz3ZgtcZ3q7Kd2dhbV7U/pGIAIt0epMORaKnWbZZutjkL4kcpaIIuTfQKciy00G30dTE5xDOmDZV64O/jACVUGo5o0OTuTOma2levMYbyHY2GdUQHpqi+dMjQq4N1MxMhZGt+l0TqZ48i38HB5a86hsJ63+WPg0qomzVN4ZIlSyCTNgv1TaIiQYlVj91R0MahoslSA1xvkcmEt4MJneuRM1qROYYX5xLiiUr15b+xiXqDQeemrGosN5CYxqFQNYM9w4Pg3Pge5o462+026dmlVg0zeiLJCTmHp1M57S88hFBuVsiu3eCOSL5cOcBHqQs+R3+F251IkyRjqEphgGkRCrNXcpE5gjKEAv+nBgbRREAUt3R3dCKthpFyM3ljbmZIL+CmyoBbrzNz5djkpGLzNo7ddlJJoV+GmVGZlpo/32CIXPBGgHS5MfSeC2QSwnwF9xkfrGf6Mhk5UBOwDGI9+pUIzbePX21gxiufnxhXXTCJUgEQDmCr2c=
after_success:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
deploy:
  provider: script
  script: yarn run publish
  skip_cleanup: true
  on:
    tags: true
    repo: 8base/js-sdk
    branch: master
